# Generated by Django 4.2 on 2025-02-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lang_translated_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
