# Generated by Django 4.2 on 2025-02-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_lang_translated_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='lang_translated_content',
        ),
    ]
